const WORDS = [
 {
  "id": "d1-01",
  "day": 1,
  "word": "return",
  "ipa": "/rɪˈtɜːrn/",
  "pos": "v / n / adj",
  "zh": "n. 回来；返回；来回票",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 turn → return",
  "coll": "return home；return journey",
  "cefr": "A1",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "He returned to his hometown after ten years abroad.",
  "sentZh": "他在国外生活十年后回到了家乡。"
 },
 {
  "id": "d1-02",
  "day": 1,
  "word": "reject",
  "ipa": "/rɪˈdʒekt/",
  "pos": "v / n",
  "zh": "n. 被拒之人；被弃之物；不合格品",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 ject → reject",
  "coll": "reject both；we reject",
  "cefr": "A2",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "The committee rejected the proposal due to budget concerns.",
  "sentZh": "委员会因预算问题否决了这项提案。"
 },
 {
  "id": "d1-03",
  "day": 1,
  "word": "reduce",
  "ipa": "/rɪˈduːs/",
  "pos": "v",
  "zh": "vt. 减少；分解；降低",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 duce → reduce",
  "coll": "reduce costs；reduce heat",
  "cefr": "A1",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "The company reduced costs by cutting unnecessary travel.",
  "sentZh": "公司通过削减不必要的差旅降低了成本。"
 },
 {
  "id": "d1-04",
  "day": 1,
  "word": "rejuvenate",
  "ipa": "/rɪˈdʒuːvəneɪt/",
  "pos": "v",
  "zh": "vt. 使年轻；使复原；使恢复精神",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 juven + 后缀 -ate（动词：使/做） → rejuvenate",
  "coll": "rejuvenate itself；rejuvenate themselves",
  "cefr": "C1",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "A short vacation by the sea can rejuvenate a tired mind.",
  "sentZh": "海边小住几日能让疲惫的头脑恢复活力。"
 },
 {
  "id": "d1-05",
  "day": 1,
  "word": "reverberate",
  "ipa": "/rɪˈvɜːrbəreɪt/",
  "pos": "v / adj",
  "zh": "vi. 回响；反响；被反射",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 verber + 后缀 -ate（动词：使/做） → reverberate",
  "coll": "reverberate through；reverberate throughout",
  "cefr": "C1",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "Thunder reverberated through the valley all night.",
  "sentZh": "雷声整夜在山谷中回荡。"
 },
 {
  "id": "d1-06",
  "day": 1,
  "word": "resent",
  "ipa": "/rɪˈzent/",
  "pos": "v",
  "zh": "vt. 愤恨；憎恶；怨恨",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 sent → resent",
  "coll": "resent being；resent having",
  "cefr": "B1",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "She resents being interrupted while she is studying.",
  "sentZh": "她讨厌学习时被打断。"
 },
 {
  "id": "d1-07",
  "day": 1,
  "word": "resentful",
  "ipa": "/rɪˈzentfl/",
  "pos": "adj",
  "zh": "a. 岔恨的；易怨恨的；不满的",
  "decomp": "前缀 re-（再次；返回） + 词根/词干 sentful → resentful",
  "coll": "resentful about；resentful toward",
  "cefr": "B2",
  "affix": "re-",
  "affixMeaning": "返回、再次、反向 / back, again",
  "series": "方向-回/反",
  "sent": "He felt resentful about the unfair treatment.",
  "sentZh": "他对不公平的对待心怀不满。"
 },
 {
  "id": "d1-08",
  "day": 1,
  "word": "president",
  "ipa": "/ˈprezɪdənt/",
  "pos": "n",
  "zh": "n. 总统；总裁；董事长",
  "decomp": "前缀 pre-（在前） + 词根/词干 sid + 后缀 -ent（名词/形容词后缀） → president",
  "coll": "president roosevelt；president wilson",
  "cefr": "A1",
  "affix": "pre-",
  "affixMeaning": "在前、预先 / before, beforehand",
  "series": "时间-前",
  "sent": "The president delivered a speech at the graduation ceremony.",
  "sentZh": "校长在毕业典礼上发表了讲话。"
 },
 {
  "id": "d1-09",
  "day": 1,
  "word": "prejudice",
  "ipa": "/ˈpredʒudɪs/",
  "pos": "v / n",
  "zh": "n. 偏见；成见；侵害",
  "decomp": "前缀 pre-（在前） + 词根/词干 judice → prejudice",
  "coll": "prejudice against；prejudice toward",
  "cefr": "B1",
  "affix": "pre-",
  "affixMeaning": "在前、预先 / before, beforehand",
  "series": "时间-前",
  "sent": "Travel helps reduce prejudice against foreign cultures.",
  "sentZh": "旅行有助于减少对外国文化的偏见。"
 },
 {
  "id": "d1-10",
  "day": 1,
  "word": "prescription",
  "ipa": "/prɪˈskrɪpʃn/",
  "pos": "n",
  "zh": "n. 处方；命令；指定",
  "decomp": "前缀 pre-（在前） + 词根/词干 scrip + 后缀 -tion（名词化：行为/过程） → prescription",
  "coll": "prescription drugs；prescription drug",
  "cefr": "B1",
  "affix": "pre-",
  "affixMeaning": "在前、预先 / before, beforehand",
  "series": "时间-前",
  "sent": "You need a doctor's prescription to buy this medicine.",
  "sentZh": "购买这种药需要医生的处方。"
 },
 {
  "id": "d1-11",
  "day": 1,
  "word": "forecast",
  "ipa": "/ˈfɔːrkæst/",
  "pos": "v / n",
  "zh": "n. 预想；预测；预报",
  "decomp": "前缀 fore-（在前） + 词根/词干 cast → forecast",
  "coll": "forecast error；forecast errors",
  "cefr": "B1",
  "affix": "fore-",
  "affixMeaning": "在前、预先 / before, beforehand",
  "series": "时间-前",
  "sent": "The weather forecast says it will rain tomorrow.",
  "sentZh": "天气预报说明天有雨。"
 },
 {
  "id": "d1-12",
  "day": 1,
  "word": "foretell",
  "ipa": "/fɔːrˈtel/",
  "pos": "v",
  "zh": "vt. 预言；预告；预示",
  "decomp": "前缀 fore-（在前） + 词根/词干 tell → foretell",
  "coll": "foretell future；foretell events",
  "cefr": "C2",
  "affix": "fore-",
  "affixMeaning": "在前、预先 / before, beforehand",
  "series": "时间-前",
  "sent": "No one can foretell what will happen next century.",
  "sentZh": "没有人能预言下个世纪会发生什么。"
 },
 {
  "id": "d1-13",
  "day": 1,
  "word": "foresee",
  "ipa": "/fɔːrˈsiː/",
  "pos": "v",
  "zh": "vt. 预见；预知",
  "decomp": "前缀 fore-（在前） + 词根/词干 see → foresee",
  "coll": "foresee future；we foresee",
  "cefr": "B1",
  "affix": "fore-",
  "affixMeaning": "在前、预先 / before, beforehand",
  "series": "时间-前",
  "sent": "The engineers foresaw potential problems with the design.",
  "sentZh": "工程师们预见到了设计中的潜在问题。"
 },
 {
  "id": "d1-14",
  "day": 1,
  "word": "post-war",
  "ipa": "/ˌpoʊst ˈwɔːr/",
  "pos": "adj",
  "zh": "a. 战后的",
  "decomp": "前缀 post-（在后） + 词根/词干 war → post-war",
  "coll": "post-war + noun",
  "cefr": "C1",
  "affix": "post-",
  "affixMeaning": "在后、以后 / after, behind",
  "series": "时间-后",
  "sent": "The post-war period brought rapid economic growth.",
  "sentZh": "战后时期带来了快速的经济增长。"
 },
 {
  "id": "d1-15",
  "day": 1,
  "word": "postgraduate",
  "ipa": "/ˌpoʊst ˈɡrædʒuət/",
  "pos": "n / adj",
  "zh": "a. 大学毕业后的；大学研究院的；n. 研究生",
  "decomp": "前缀 post-（在后） + 词根/词干 gradu + 后缀 -ate（动词：使/做） → postgraduate",
  "coll": "postgraduate students；postgraduate training",
  "cefr": "B2",
  "affix": "post-",
  "affixMeaning": "在后、以后 / after, behind",
  "series": "时间-后",
  "sent": "She is pursuing a postgraduate degree in linguistics.",
  "sentZh": "她正在攻读语言学研究生学位。"
 },
 {
  "id": "d1-16",
  "day": 1,
  "word": "postpone",
  "ipa": "/poʊstˈpoʊn/",
  "pos": "v",
  "zh": "vt. 延迟；使延期；缓办",
  "decomp": "前缀 post-（在后） + 词根/词干 pone → postpone",
  "coll": "postpone indefinitely；postpone action",
  "cefr": "B1",
  "affix": "post-",
  "affixMeaning": "在后、以后 / after, behind",
  "series": "时间-后",
  "sent": "The meeting was postponed until next Friday.",
  "sentZh": "会议被推迟到了下周五。"
 },
 {
  "id": "d1-17",
  "day": 1,
  "word": "prolong",
  "ipa": "/prəˈlɔːŋ/",
  "pos": "v",
  "zh": "vt. 延长；拖延；拖长",
  "decomp": "前缀 pro-（向前；支持） + 词根/词干 long → prolong",
  "coll": "prolong life；prolong survival",
  "cefr": "B2",
  "affix": "pro-",
  "affixMeaning": "向前、支持 / forward, for",
  "series": "方向-向前",
  "sent": "Regular exercise can prolong your life.",
  "sentZh": "经常锻炼可以延年益寿。"
 },
 {
  "id": "d1-18",
  "day": 1,
  "word": "promote",
  "ipa": "/prəˈmoʊt/",
  "pos": "v",
  "zh": "vt. 促进；晋升；创办",
  "decomp": "前缀 pro-（向前；支持） + 词根/词干 mote → promote",
  "coll": "promote economic；promote social",
  "cefr": "A2",
  "affix": "pro-",
  "affixMeaning": "向前、支持 / forward, for",
  "series": "方向-向前",
  "sent": "The campaign aims to promote healthy eating habits.",
  "sentZh": "这项活动旨在促进健康的饮食习惯。"
 },
 {
  "id": "d1-19",
  "day": 1,
  "word": "proliferate",
  "ipa": "/prəˈlɪfəreɪt/",
  "pos": "v",
  "zh": "vi. 增殖；激增；扩散",
  "decomp": "前缀 pro-（向前；支持） + 词根/词干 lifer + 后缀 -ate（动词：使/做） → proliferate",
  "coll": "proliferate rapidly；proliferate into",
  "cefr": "C1",
  "affix": "pro-",
  "affixMeaning": "向前、支持 / forward, for",
  "series": "方向-向前",
  "sent": "Smartphones have proliferated in almost every country.",
  "sentZh": "智能手机几乎在每个国家都迅速普及。"
 },
 {
  "id": "d1-20",
  "day": 1,
  "word": "prominent",
  "ipa": "/ˈprɑːmɪnənt/",
  "pos": "adj",
  "zh": "a. 卓越的；显著的；突出的",
  "decomp": "前缀 pro-（向前；支持） + 词根/词干 min + 后缀 -ent（名词/形容词后缀） → prominent",
  "coll": "prominent part；prominent place",
  "cefr": "B1",
  "affix": "pro-",
  "affixMeaning": "向前、支持 / forward, for",
  "series": "方向-向前",
  "sent": "She played a prominent role in the research project.",
  "sentZh": "她在这项研究项目中发挥了重要作用。"
 },
 {
  "id": "d2-01",
  "day": 2,
  "word": "surface",
  "ipa": "/ˈsɜːrfɪs/",
  "pos": "v / n / adj",
  "zh": "n. 面；表面；水面",
  "decomp": "前缀 sur-（在上） + 词根/词干 face → surface",
  "coll": "surface area；surface tension",
  "cefr": "A1",
  "affix": "super-/sur-",
  "affixMeaning": "向上、超过 / above, beyond",
  "series": "方向-向上",
  "sent": "The surface of the lake was perfectly calm at dawn.",
  "sentZh": "黎明时湖面平静如镜。"
 },
 {
  "id": "d2-02",
  "day": 2,
  "word": "surmount",
  "ipa": "/sərˈmaʊnt/",
  "pos": "v",
  "zh": "vt. 战胜；超越；克服",
  "decomp": "前缀 sur-（在上） + 词根/词干 mount → surmount",
  "coll": "surmount obstacles；surmount difficulties",
  "cefr": "B2",
  "affix": "super-/sur-",
  "affixMeaning": "向上、超过 / above, beyond",
  "series": "方向-向上",
  "sent": "She managed to surmount every difficulty in her studies.",
  "sentZh": "她设法克服了学习中的每一个困难。"
 },
 {
  "id": "d2-03",
  "day": 2,
  "word": "superior",
  "ipa": "/suːˈpɪriər/",
  "pos": "n / adj",
  "zh": "n. 长者；占优势的人；上级",
  "decomp": "前缀 super-（在上；超过） + 词根/词干 ior → superior",
  "coll": "superior court；superior force",
  "cefr": "B1",
  "affix": "super-/sur-",
  "affixMeaning": "向上、超过 / above, beyond",
  "series": "方向-向上",
  "sent": "This laptop is superior to the older model in every way.",
  "sentZh": "这台笔记本电脑在各方面都优于旧款。"
 },
 {
  "id": "d2-04",
  "day": 2,
  "word": "superb",
  "ipa": "/suːˈpɜːrb/",
  "pos": "adj",
  "zh": "a. 极度的；华丽的；极好的",
  "decomp": "词根/词干 superb → superb",
  "coll": "superb example；superb view",
  "cefr": "B1",
  "affix": "super-/sur-",
  "affixMeaning": "向上、超过 / above, beyond",
  "series": "方向-向上",
  "sent": "The orchestra gave a superb performance last night.",
  "sentZh": "交响乐团昨晚的演出精彩绝伦。"
 },
 {
  "id": "d2-05",
  "day": 2,
  "word": "supreme",
  "ipa": "/suːˈpriːm/",
  "pos": "n / adj",
  "zh": "n. 至高；霸权；a. 至高的",
  "decomp": "词根/词干 supreme → supreme",
  "coll": "supreme court；supreme being",
  "cefr": "A2",
  "affix": "super-/sur-",
  "affixMeaning": "向上、超过 / above, beyond",
  "series": "方向-向上",
  "sent": "The Supreme Court made a landmark decision last month.",
  "sentZh": "最高法院上个月做出了一项里程碑式的裁决。"
 },
 {
  "id": "d2-06",
  "day": 2,
  "word": "overall",
  "ipa": "/ˌoʊvərˈɔːl/",
  "pos": "adj / v / n",
  "zh": "a. 全部的；全体的；从头至尾的",
  "decomp": "前缀 over-（在上；过度） + 词根/词干 all → overall",
  "coll": "overall effect；overall performance",
  "cefr": "A2",
  "affix": "over-",
  "affixMeaning": "在上、过度 / above, excessively",
  "series": "方向-向上",
  "sent": "The overall quality of the essay has improved.",
  "sentZh": "这篇文章的整体质量有所提高。"
 },
 {
  "id": "d2-07",
  "day": 2,
  "word": "overcome",
  "ipa": "/ˌoʊvərˈkʌm/",
  "pos": "v",
  "zh": "vt. 战胜；克服；胜过",
  "decomp": "前缀 over-（在上；过度） + 词根/词干 come → overcome",
  "coll": "overcome before；been overcome",
  "cefr": "A2",
  "affix": "over-",
  "affixMeaning": "在上、过度 / above, excessively",
  "series": "方向-向上",
  "sent": "He overcame his fear of public speaking through practice.",
  "sentZh": "他通过练习克服了对公开演讲的恐惧。"
 },
 {
  "id": "d2-08",
  "day": 2,
  "word": "overlook",
  "ipa": "/ˌoʊvərˈlʊk/",
  "pos": "v / n",
  "zh": "vt. 俯瞰；远眺；没注意到",
  "decomp": "前缀 over-（在上；过度） + 词根/词干 look → overlook",
  "coll": "overlook press；we overlook",
  "cefr": "B1",
  "affix": "over-",
  "affixMeaning": "在上、过度 / above, excessively",
  "series": "方向-向上",
  "sent": "Don't overlook the small details in the contract.",
  "sentZh": "不要忽视合同中的细节。"
 },
 {
  "id": "d2-09",
  "day": 2,
  "word": "overestimate",
  "ipa": "/ˌoʊvərˈestɪmeɪt/",
  "pos": "v / n",
  "zh": "vt. 评价过高；过高估价；n. 估计过高",
  "decomp": "前缀 over-（在上；过度） + 词根/词干 estim + 后缀 -ate（动词：使/做） → overestimate",
  "coll": "overestimate both；overestimate actual",
  "cefr": "C1",
  "affix": "over-",
  "affixMeaning": "在上、过度 / above, excessively",
  "series": "方向-向上",
  "sent": "We tend to overestimate how much we can finish in one day.",
  "sentZh": "我们往往高估一天内能完成的工作量。"
 },
 {
  "id": "d2-10",
  "day": 2,
  "word": "decline",
  "ipa": "/dɪˈklaɪn/",
  "pos": "v / n",
  "zh": "n. 衰退；跌落；下降",
  "decomp": "前缀 de-（向下；去除） + 词根/词干 cline → decline",
  "coll": "decline during；decline after",
  "cefr": "A2",
  "affix": "de-",
  "affixMeaning": "向下、减少、离开 / down, reduce, away",
  "series": "方向-向下",
  "sent": "Sales began to decline after the holiday season.",
  "sentZh": "假日季过后销售额开始下滑。"
 },
 {
  "id": "d2-11",
  "day": 2,
  "word": "decrease",
  "ipa": "/dɪˈkriːs/",
  "pos": "v / n",
  "zh": "n. 减少；减少量；v. 减少",
  "decomp": "前缀 de-（向下；去除） + 词根/词干 crease → decrease",
  "coll": "decrease during；decrease over",
  "cefr": "B1",
  "affix": "de-",
  "affixMeaning": "向下、减少、离开 / down, reduce, away",
  "series": "方向-向下",
  "sent": "The medicine gradually decreased the patient's pain.",
  "sentZh": "药物逐渐减轻了病人的疼痛。"
 },
 {
  "id": "d2-12",
  "day": 2,
  "word": "depend",
  "ipa": "/dɪˈpend/",
  "pos": "v",
  "zh": "vi. 靠；视...而定；信赖",
  "decomp": "前缀 de-（向下；去除） + 词根/词干 pend → depend",
  "coll": "depend upon；depend largely",
  "cefr": "A1",
  "affix": "de-",
  "affixMeaning": "向下、减少、离开 / down, reduce, away",
  "series": "方向-向下",
  "sent": "Crop yields depend heavily on the weather.",
  "sentZh": "农作物产量很大程度上取决于天气。"
 },
 {
  "id": "d2-13",
  "day": 2,
  "word": "underground",
  "ipa": "/ˈʌndərɡraʊnd/",
  "pos": "adj / v / n",
  "zh": "n. 地下；地铁；地道",
  "decomp": "前缀 under-（在下） + 词根/词干 ground → underground",
  "coll": "underground railroad；underground water",
  "cefr": "B1",
  "affix": "under-",
  "affixMeaning": "在下、不足 / under, below, insufficient",
  "series": "方向-向下",
  "sent": "They took the underground to the museum this morning.",
  "sentZh": "他们今天早上乘地铁去了博物馆。"
 },
 {
  "id": "d2-14",
  "day": 2,
  "word": "underline",
  "ipa": "/ˌʌndərˈlaɪn/",
  "pos": "v / n",
  "zh": "vt. 在...下面划线；作...的衬里；强调",
  "decomp": "前缀 under-（在下） + 词根/词干 line → underline",
  "coll": "underline key；underline button",
  "cefr": "B1",
  "affix": "under-",
  "affixMeaning": "在下、不足 / under, below, insufficient",
  "series": "方向-向下",
  "sent": "Please underline the key terms in the reading passage.",
  "sentZh": "请在阅读文章中的关键术语下面划线。"
 },
 {
  "id": "d2-15",
  "day": 2,
  "word": "suburb",
  "ipa": "/ˈsʌbɜːrb/",
  "pos": "n",
  "zh": "n. 市郊住宅区；郊区；边缘",
  "decomp": "前缀 sub-（在下） + 词根/词干 urb → suburb",
  "coll": "suburb called；suburb near",
  "cefr": "B1",
  "affix": "sub-/suc-/suf-/sus-",
  "affixMeaning": "在下、次级 / under, below, secondary",
  "series": "方向-向下",
  "sent": "Many families moved to the suburbs for better schools.",
  "sentZh": "许多家庭为了更好的学校搬到了郊区。"
 },
 {
  "id": "d2-16",
  "day": 2,
  "word": "submarine",
  "ipa": "/ˌsʌbməˈriːn/",
  "pos": "v / n / adj",
  "zh": "n. 潜水艇；海底生物；a. 海中的",
  "decomp": "前缀 sub-（在下） + 词根/词干 marine → submarine",
  "coll": "submarine warfare；submarine cable",
  "cefr": "B2",
  "affix": "sub-/suc-/suf-/sus-",
  "affixMeaning": "在下、次级 / under, below, secondary",
  "series": "方向-向下",
  "sent": "The submarine can dive to a depth of 500 meters.",
  "sentZh": "这艘潜艇能下潜到五百米深。"
 },
 {
  "id": "d2-17",
  "day": 2,
  "word": "subtropical",
  "ipa": "/ˌsʌbˈtrɑːpɪkl/",
  "pos": "adj",
  "zh": "a. 亚热带的；亚热带的",
  "decomp": "前缀 sub-（在下） + 词根/词干 trop + 后缀 -ical（形容词：与……有关） → subtropical",
  "coll": "subtropical regions；subtropical climate",
  "cefr": "C2",
  "affix": "sub-/suc-/suf-/sus-",
  "affixMeaning": "在下、次级 / under, below, secondary",
  "series": "方向-向下",
  "sent": "Florida enjoys a subtropical climate with mild winters.",
  "sentZh": "佛罗里达属亚热带气候，冬季温和。"
 },
 {
  "id": "d2-18",
  "day": 2,
  "word": "succeed",
  "ipa": "/səkˈsiːd/",
  "pos": "v",
  "zh": "vi. 成功；继承；继续",
  "decomp": "前缀 suc-（在下） + 词根/词干 ce + 后缀 -ed（过去分词/形容词后缀） → succeed",
  "coll": "succeed only；succeed without",
  "cefr": "A2",
  "affix": "sub-/suc-/suf-/sus-",
  "affixMeaning": "在下、次级 / under, below, secondary",
  "series": "方向-向下",
  "sent": "She succeeded in passing the TOEFL test on her first attempt.",
  "sentZh": "她第一次参加托福考试就顺利通过。"
 },
 {
  "id": "d2-19",
  "day": 2,
  "word": "suffer",
  "ipa": "/ˈsʌfər/",
  "pos": "v",
  "zh": "vt. 遭受；经历；忍受",
  "decomp": "前缀 suf-（在下） + 词根/词干 fer → suffer",
  "coll": "suffer death；suffer much",
  "cefr": "A1",
  "affix": "sub-/suc-/suf-/sus-",
  "affixMeaning": "在下、次级 / under, below, secondary",
  "series": "方向-向下",
  "sent": "The region suffered severe droughts last summer.",
  "sentZh": "该地区去年夏天遭受了严重干旱。"
 },
 {
  "id": "d2-20",
  "day": 2,
  "word": "sustain",
  "ipa": "/səˈsteɪn/",
  "pos": "v",
  "zh": "vt. 承受；支持；供养",
  "decomp": "前缀 sus-（在下） + 词根/词干 tain → sustain",
  "coll": "sustain life；sustain itself",
  "cefr": "A2",
  "affix": "sub-/suc-/suf-/sus-",
  "affixMeaning": "在下、次级 / under, below, secondary",
  "series": "方向-向下",
  "sent": "The economy has sustained steady growth for five years.",
  "sentZh": "该经济体已保持五年的稳定增长。"
 },
 {
  "id": "d3-01",
  "day": 3,
  "word": "missile",
  "ipa": "/ˈmɪsl/",
  "pos": "n / adj",
  "zh": "n. 发射物；导弹；飞弹",
  "decomp": "前缀 mis-（错误地） + 词根 mit/miss（送、放） + 词干 sile → missile",
  "coll": "missile crisis；missile defense",
  "cefr": "B1",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "The military tested a new guided missile this week.",
  "sentZh": "军方本周测试了一枚新的制导导弹。"
 },
 {
  "id": "d3-02",
  "day": 3,
  "word": "dismiss",
  "ipa": "/dɪsˈmɪs/",
  "pos": "v",
  "zh": "vt. 解散；开除；解职",
  "decomp": "前缀 dis-（不；分离） + 词根 mit/miss（送、放） → dismiss",
  "coll": "dismiss you；we dismiss",
  "cefr": "A2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "The teacher dismissed the class five minutes early.",
  "sentZh": "老师提前五分钟下了课。"
 },
 {
  "id": "d3-03",
  "day": 3,
  "word": "promise",
  "ipa": "/ˈprɑːmɪs/",
  "pos": "v / n",
  "zh": "n. 诺言；约定的事情；有指望",
  "decomp": "前缀 pro-（向前；支持） + 词根 mit/miss（送、放） + 词干 mise → promise",
  "coll": "promise you；promise made",
  "cefr": "A2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "He kept his promise to help her with the assignment.",
  "sentZh": "他信守了帮她完成作业的承诺。"
 },
 {
  "id": "d3-04",
  "day": 3,
  "word": "emit",
  "ipa": "/ɪˈmɪt/",
  "pos": "v",
  "zh": "vt. 发出；放射；发表(意见等)",
  "decomp": "前缀 em-（使进入） + 词根 mit/miss（送、放） + 词干 it → emit",
  "coll": "emit light；emit bills",
  "cefr": "B2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "Older cars emit more pollutants than modern ones.",
  "sentZh": "旧车比现代汽车排放更多污染物。"
 },
 {
  "id": "d3-05",
  "day": 3,
  "word": "admit",
  "ipa": "/ədˈmɪt/",
  "pos": "v",
  "zh": "vt. 承认；接受；允许进入",
  "decomp": "前缀 ad-（朝向） + 词根 mit/miss（送、放） → admit",
  "coll": "admit i；admit he",
  "cefr": "B1",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "The university admitted over two thousand new students this fall.",
  "sentZh": "这所大学今年秋季录取了两千多名新生。"
 },
 {
  "id": "d3-06",
  "day": 3,
  "word": "admission",
  "ipa": "/ədˈmɪʃn/",
  "pos": "n",
  "zh": "n. 准许进入；入场费；录用",
  "decomp": "前缀 ad-（朝向） + 词根 mit/miss（送、放） + 词干 mis + 后缀 -sion（名词化：行为/状态） → admission",
  "coll": "admission into；admission requirements",
  "cefr": "A2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "Admission to the museum is free on Sundays.",
  "sentZh": "周日博物馆免费开放。"
 },
 {
  "id": "d3-07",
  "day": 3,
  "word": "commit",
  "ipa": "/kəˈmɪt/",
  "pos": "v",
  "zh": "vt. 委托(托付)；犯罪；指派...作战",
  "decomp": "前缀 com-（共同） + 词根 mit/miss（送、放） → commit",
  "coll": "commit suicide；commit themselves",
  "cefr": "A2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "The government committed funds to renewable energy research.",
  "sentZh": "政府为可再生能源研究拨出了专项资金。"
 },
 {
  "id": "d3-08",
  "day": 3,
  "word": "commitment",
  "ipa": "/kəˈmɪtmənt/",
  "pos": "n",
  "zh": "n. 委托；交押；承担义务",
  "decomp": "前缀 com-（共同） + 词根 mit/miss（送、放） + 后缀 -ment（名词化：行为/结果） → commitment",
  "coll": "commitment are；political commitment",
  "cefr": "A2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "Learning a language requires long-term commitment.",
  "sentZh": "学习一门语言需要长期的投入。"
 },
 {
  "id": "d3-09",
  "day": 3,
  "word": "omit",
  "ipa": "/oʊˈmɪt/",
  "pos": "v",
  "zh": "vt. 省略；删除；疏忽",
  "decomp": "词根 mit/miss（送、放） → omit",
  "coll": "omit nothing；omit many",
  "cefr": "B1",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "He omitted an important detail in his report.",
  "sentZh": "他在报告中遗漏了一个重要细节。"
 },
 {
  "id": "d3-10",
  "day": 3,
  "word": "submit",
  "ipa": "/səbˈmɪt/",
  "pos": "v",
  "zh": "vt. 使服从；使受到；委托",
  "decomp": "前缀 sub-（在下） + 词根 mit/miss（送、放） → submit",
  "coll": "submit themselves；submit himself",
  "cefr": "A2",
  "affix": "mit/miss",
  "affixMeaning": "送、放 / send, let go",
  "series": "基础",
  "sent": "Students must submit their essays before Friday.",
  "sentZh": "学生必须在周五之前提交作文。"
 },
 {
  "id": "d3-11",
  "day": 3,
  "word": "describe",
  "ipa": "/dɪˈskraɪb/",
  "pos": "v",
  "zh": "vt. 描述；描绘；画",
  "decomp": "前缀 de-（向下；去除） + 词根 scrib/script（写） → describe",
  "coll": "we describe；they describe",
  "cefr": "A1",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "The witness described the suspect in great detail.",
  "sentZh": "目击者详细描述了嫌疑人的特征。"
 },
 {
  "id": "d3-12",
  "day": 3,
  "word": "description",
  "ipa": "/dɪˈskrɪpʃn/",
  "pos": "n",
  "zh": "n. 描述；说明；种类",
  "decomp": "前缀 de-（向下；去除） + 词根 scrib/script（写） + 词干 scrip + 后缀 -tion（名词化：行为/过程） → description",
  "coll": "description given；description are",
  "cefr": "A2",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "The job description lists strong writing skills as a requirement.",
  "sentZh": "职位描述将较强的写作能力列为要求之一。"
 },
 {
  "id": "d3-13",
  "day": 3,
  "word": "script",
  "ipa": "/skrɪpt/",
  "pos": "v / n",
  "zh": "n. 手迹；手稿；正本",
  "decomp": "词根 scrib/script（写） → script",
  "coll": "script file；script editor",
  "cefr": "B1",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "The professor wrote a script for the documentary.",
  "sentZh": "教授为这部纪录片撰写了解说词。"
 },
 {
  "id": "d3-14",
  "day": 3,
  "word": "ascribe",
  "ipa": "/əˈskraɪb/",
  "pos": "v",
  "zh": "vt. 归因于；归咎于；归咎于",
  "decomp": "前缀 a-（朝向） + 词根 scrib/script（写） → ascribe",
  "coll": "ascribe much；ascribe meaning",
  "cefr": "B2",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "Researchers ascribe the warming trend to greenhouse gases.",
  "sentZh": "研究人员将变暖趋势归因于温室气体。"
 },
 {
  "id": "d3-15",
  "day": 3,
  "word": "subscribe",
  "ipa": "/səbˈskraɪb/",
  "pos": "v",
  "zh": "vt. 捐献；签署；vi. 赞成",
  "decomp": "前缀 sub-（在下） + 词根 scrib/script（写） → subscribe",
  "coll": "subscribe myself；subscribe now",
  "cefr": "B2",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "I subscribe to several academic journals online.",
  "sentZh": "我在线订阅了几种学术期刊。"
 },
 {
  "id": "d3-16",
  "day": 3,
  "word": "subscription",
  "ipa": "/səbˈskrɪpʃn/",
  "pos": "n",
  "zh": "n. 捐献；订金；订阅",
  "decomp": "前缀 sub-（在下） + 词根 scrib/script（写） + 词干 scrip + 后缀 -tion（名词化：行为/过程） → subscription",
  "coll": "subscription price；subscription rates",
  "cefr": "B1",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "The library's subscription covers over a hundred databases.",
  "sentZh": "图书馆的订阅涵盖一百多个数据库。"
 },
 {
  "id": "d3-17",
  "day": 3,
  "word": "circumscribe",
  "ipa": "/ˈsɜːrkəmskraɪb/",
  "pos": "v",
  "zh": "vt. 在...周围画线；限制",
  "decomp": "前缀 circum-（周围） + 词根 scrib/script（写） → circumscribe",
  "coll": "circumscribe women；circumscribe human",
  "cefr": "C1",
  "affix": "scrib/script",
  "affixMeaning": "写 / write",
  "series": "基础",
  "sent": "New rules circumscribe the powers of local officials.",
  "sentZh": "新规定限制了地方官员的权力。"
 },
 {
  "id": "d3-18",
  "day": 3,
  "word": "inspire",
  "ipa": "/ɪnˈspaɪər/",
  "pos": "v",
  "zh": "vt. 使感动；激发；启示",
  "decomp": "前缀 in-（进入；在内） + 词根 spir（呼吸） → inspire",
  "coll": "inspire confidence；inspire us",
  "cefr": "B1",
  "affix": "spir",
  "affixMeaning": "呼吸 / breathe",
  "series": "基础",
  "sent": "Her story inspired millions of young readers.",
  "sentZh": "她的故事激励了数百万年轻读者。"
 },
 {
  "id": "d3-19",
  "day": 3,
  "word": "aspiration",
  "ipa": "/ˌæspəˈreɪʃn/",
  "pos": "n",
  "zh": "n. 热望；志向；渴望",
  "decomp": "前缀 a-（朝向） + 词根 spir（呼吸） + 后缀 -ation（名词化：行为/过程） → aspiration",
  "coll": "aspiration biopsy；aspiration pneumonia",
  "cefr": "C1",
  "affix": "spir",
  "affixMeaning": "呼吸 / breathe",
  "series": "基础",
  "sent": "He has a strong aspiration to study abroad.",
  "sentZh": "他有强烈的出国留学的愿望。"
 },
 {
  "id": "d3-20",
  "day": 3,
  "word": "expire",
  "ipa": "/ɪkˈspaɪər/",
  "pos": "v",
  "zh": "vi. 期满；呼气；断气",
  "decomp": "前缀 ex-（向外） + 词根 spir（呼吸） + 词干 pire → expire",
  "coll": "expire before；expire until",
  "cefr": "B2",
  "affix": "spir",
  "affixMeaning": "呼吸 / breathe",
  "series": "基础",
  "sent": "My passport will expire next month, so I must renew it.",
  "sentZh": "我的护照下个月到期，必须办理续期。"
 }
];
const TOTAL_WORDS = WORDS.length;
const REVIEW_DAYS = [3, 7];
const PER_DAY = 20;
